config/routes.rb
Elblog::Application.routes.draw do
   
devise_for :bloggers, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

resources :comments do
  resources :likes 
end

resources :posts do 
  resources :comments
end

root :to => "posts#index"

end

app/models/anonymous_comment.rb
class AnonymousComment < Comment
end

app/models/blogger.rb
class Blogger < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable , :registerable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me , :full_name, :blogger_id ,:provider, :uid

validates :full_name, presence: true    
validates :email, presence: true    
validates :password, presence: true   
validates :password_confirmation, presence: true 

  has_many :likes   

def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
  user = Blogger.where(:provider => auth.provider, :uid => auth.uid).first
  unless user
    user = Blogger.create(full_name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20]
                         )
  end
  user
end

def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

#Relacion
  has_many :posts
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :visitor, :message, :created_at, :post_id, :type
  belongs_to :post
  has_many :likes

  validates :visitor, presence: true
  validates :message, presence: true

end

=begin
  attr_accessible   :message, :created_at, :post_id
 
  belongs_to :post
  validates :presence => true
  validates :message, presence: true
end
=end

app/models/like.rb
class Like < ActiveRecord::Base
 
	 attr_accessible :blogger_id, :comment_id
	 belongs_to :comment
	 belongs_to :blogger
end

app/models/post.rb
class Post < ActiveRecord::Base
	attr_accessible :title , :content, :created_at, :blogger_id , :full_name, :image
	has_many :comments
	has_many :anonymous_comments
	has_many :user_comments
	belongs_to :blogger

has_attached_file :image
 
	has_attached_file :image, :styles => { :small => "300x300>" }, :default_url => "/assets/images/default.gif"
    
    validates_attachment_size :image, :less_than => 5.megabytes


end

app/models/user_comment.rb
class UserComment < Comment
	belongs_to :blogger
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
=begin
def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment]) #este parametro es el objeto creado a partir de los atributos de la clase comment
     
    if @comment.save
      CommentMailer.comment_notification(@post)
    else
      redirect_to post_path(@post), :alert => @comment.errors.full_messages.to_sentence
    end

    respond_to do |format|
      format.js
    end
  end
=end

  def create
    @post = Post.find(params[:post_id])

    if current_blogger
        @comment = @post.user_comments.build(params[:comment]) #este parametro es el objeto creado a partir de los atributos de la clase comment
   	    
      else
        @comment = @post.anonymous_comments.build(params[:comment]) #este parametro es el objeto creado a partir de los atributos de la clase comment   
    end

    if @comment.save
   		 CommentMailer.comment_notification(@post).deliver
   	  else
   		 redirect_to post_path(@post), :alert => @comment.errors.full_messages.to_sentence
   	end

    respond_to do |format|
      format.js
    end

  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        @comment = Comment.find(params[:comment_id])
     
        @like = Like.new()
        @like.comment = @comment
        @like.blogger = current_blogger
        @like.save()
     
         #edirect_to posts_path

        respond_to do |format|
          format.js
        end
    end

    def destroy
        @like = Like.find(params[:id])
        @comment = Comment.find(params[:comment_id])
        @like.destroy
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all
    
    respond_to do |format|
      format.html 
      format.json { render json: @post }
    end
  end

  def show
  	 @post = Post.find(params[:id])
     @comments = @post.comments

    respond_to do |format|
      format.html 
      format.json { render json: @post }
    end
  end

  def new
  	@post = Post.new
    respond_to do |format|
      format.html 
      format.json { render json: @post }
    end
  end
  
  def edit
  @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(params[:post])
 
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'post creado.' }
        format.json { render json: @post, post: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, post: :unprocessable_entity }
      end
    end
  end

 def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'done'}
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, post: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :ok }
    end
  end


end

app/controllers/users/omniauth_callbacks_controller.rb
 class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @blogger = Blogger.find_for_facebook_oauth(request.env["omniauth.auth"], current_blogger)

    if @blogger.persisted?
      sign_in_and_redirect @blogger, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_blogger_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def flash_class(type)
		case type
		when :alert
			"alert-error"
		when :notice
			"alert-success"
		else
			""
		end
	end

 def markdown(text)
    render = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html:true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      superscript: true
    }
    Redcarpet::Markdown.new(render, options).render(text).html_safe
  end


end #Este end cierra todo

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<% unless comment.new_record? %>
  	<div class ="comments">
    	
       
        <% if comment.likes.where(blogger_id: current_blogger.id).first.nil? %>

          <%=link_to "Like" , comment_likes_path(comment), method: :post, remote: true%>
        <% else %>  
          <%=link_to "UnLike" , comment_like_path(comment, comment.likes.first.id), method: :delete, remote: true%>
      		<% end %>
          <p>

        <strong>Autor:</strong>
      	 <%= comment.visitor %>
    	  </p>
    	  <p>
    		<strong>Comentario:</strong>
      		<%=  comment.message %> 
  	</div>
<% end %>

app/views/comments/_comments.html.erb
<div class ="comments">
     <p>
     <b>Visitante:</b>
     <%= comment.visitor %>
     </p>
     <p>
     <b>Comment:</b>
     <%= comment.message %> 
</div>

app/views/comments/create.js.erb
$('.messages').prepend('<%= escape_javascript(render(:partial => "comment", :locals => { :comment => @comment } )) %>')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>El blog de Guille </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class = "navbar navbar-fixed-top" >
	<div class = "navbar-inner">
		<div class = "container">
			<a href="/" class = "brand">Inicio</a>
			 <ul class = "nav pull-right">
				<% if blogger_signed_in? %>
						<li><%= link_to current_blogger.full_name, edit_blogger_registration_path %></li>
						<li><%= link_to "Cerrar sesion" ,destroy_blogger_session_path, method: :delete %></li>
				<% else %>
						<li><%= link_to "Registrarse", new_blogger_registration_path %></li>
						<li><%= link_to "Sign in with Facebook", blogger_omniauth_authorize_path(:facebook) %></li>
						<li><%= link_to "Iniciar sesion", new_blogger_session_path %></li>
				<% end %>
				</ul>
		</div>
	</div>
</div>

	<div class = "container">
			<% flash.each do |type, message| %>
		<div class = "alert <%= flash_class type %>" >
    		<button class="close" data-dismiss = "alert" >x</button> 
			<%= message %>
		</div>
		<% end %>
		<%= yield %>

			
	</div>
	

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post, html: {class: "form-horizontal"}, html: {:multipart => true }) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%=f.hidden_field :blogger_id, :value => current_blogger.id %>
 
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.file_field :image %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/delete.html.erb
<h1>Posts#delete</h1>
<p>Find me in app/views/posts/delete.html.erb</p>

app/views/posts/edit.html.erb
 <div class="hero-unit">
 	<h1>Editar post</h1>
</div>
 <%= render 'form' %>

 <%= link_to 'Volver', posts_path %>

app/views/posts/index.html.erb
<%#encoding:utf-8 %>
<div class="hero-unit">
  <h1>El blog de Guille</h1>
</div>

<% if blogger_signed_in? %>
  <%= link_to "Crear nuevo post", new_post_path , class: "btn btn-success" %>
<% end %>

<% @posts = Post.all(:order => "created_at DESC", :conditions => ["created_at <= ?", Time.now]) %>
<% @posts.each do |post| %>
  <div class = "posts" >
    <p>Tema: <%= markdown(post.title) %></p>
     <p>Creado por: <%= post.blogger.full_name %></p>
      <div class = "class">
        <%= time_ago_in_words(post.created_at) + " después" %> |
        <%= link_to "Mostrar", post %>
       
        <span class="admin" >
          <span class="admin" >
            <% if blogger_signed_in? %>
           
            |<%= link_to "Editar", edit_post_path(post) %> |
           

          <% end %>
        </span>
        </span>
      </div>
  </div>
<% end %>

app/views/posts/new.html.erb
 <div class="hero-unit">
 	<h1>Crear Nuevo Post</h1>
</div>
 <%= render 'form' %>

 <%= link_to 'Volver', posts_path %>

app/views/posts/show.html.erb
<p id="notice"></p>
<!--Those are the script for, tweet, for like on facebook and share -->
<div class="hero-unit">
  <h1><%=  @post.title %></h1>
  <%= image_tag @post.image.url(:small)%>

  <p>Creado por: <%=  @post.blogger.full_name %></p>
  <p><a href="https://twitter.com/share" class="twitter-share-button" data-ulr="<%=post_url(@post)%>" data-hashtags="<%= @post.title %>"  data-lang="en" data-count="none">Tweet</a>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

 </script>

<p>
    <a class = "share_button" fb-url = "<%= post_url(@post) %>" fb-title = "<%= @post.title %>" >Share on Facebook</a>
</div>


  <div class = "post">       
    
    <p><%= markdown(@post.content) %></b>
    <hr>
  </div>

<div class="row-fluid">
  <div class="span12">   
      <h2>Comentarios de visitantes</h2>
    <div class="row-fluid">
        <div class="span12">
          <div class="row-fluid">
            <div class="span6">

              <!-- Comments form right column-->
              <%= simple_form_for([@post, @post.comments.new], remote: true) do |f| %>
                <div class="field">

                 <% if blogger_signed_in? %>
                  <%=f.hidden_field :visitor, :value => current_blogger.full_name %><br />
                  <% else %>
                   <%=f.input :visitor, :label => 'Autor: ' %>
                  <%end%>
                </div>
                <div class="field">
                  <%=  f.input :message, :label => 'Escriba su comentario', :input_html => { class: "text_area_custom" }  %><br />           
                </div>
                <div class="actions">
                  <%= f.button :submit %>
                </div>
              <% end %>
            </div>       

            <!-- Left column -->
            <div class="span6 messages">
              <%= render :partial => 'comments/comment', :collection => @comments %> 
            </div>
        </div>
      </div>
    </div> 
  </div>
</div>

<script src='http://connect.facebook.net/en_US/all.js'></script> 
  
       
<%= link_to 'volver', posts_path %>